# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFwdKKoB-nyQwr0-nZmGox1_4JLyEvfY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    auc
)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Embedding,
    Dense,
    Dropout,
    LSTM,
    GRU,
    Bidirectional,
    Conv1D,
    GlobalMaxPooling1D
)

import tensorflow as tf

df = pd.read_csv('/content/amazon_reviews.csv')

df.head()

print(df.shape)

df.info()

df.isnull().sum()

plt.figure(figsize=(6,6))

df['sentiment'] = df['overall'].apply(lambda x: 'Positive' if x > 3 else 'Negative')

df['sentiment'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title('Sentiment Distribution')

plt.ylabel('')

plt.show()

df['review_length'] = df['reviewText'].astype(str).apply(len)
plt.figure(figsize=(10,5))

plt.hist(
    df['review_length'],
    bins=50
)

plt.title('Review Length Distribution')

plt.xlabel('Characters')

plt.ylabel('Frequency')

plt.show()

X = df['reviewText'].astype(str)

y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

max_words = 10000

tokenizer = Tokenizer(
    num_words=max_words,
    oov_token='<OOV>'
)

tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)

X_test_seq = tokenizer.texts_to_sequences(X_test)

max_len = 200

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=max_len,
    padding='post'
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=max_len,
    padding='post'
)

cnn = Sequential([

    Embedding(max_words,128),

    Conv1D(
        filters=128,
        kernel_size=5,
        activation='relu'
    ),

    GlobalMaxPooling1D(),

    Dense(64,activation='relu'),

    Dropout(0.3),

    Dense(1,activation='sigmoid')

])

cnn.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Convert y_train and y_test from string labels to numerical labels
y_train_encoded = y_train.map({'Negative': 0, 'Positive': 1})
y_test_encoded = y_test.map({'Negative': 0, 'Positive': 1})

cnn.fit(
    X_train_pad,
    y_train_encoded,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

lstm = Sequential([

    Embedding(max_words,128),

    LSTM(64),

    Dropout(0.3),

    Dense(1,activation='sigmoid')

])

lstm.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

lstm.fit(
    X_train_pad,
    y_train_encoded,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

bilstm = Sequential([

    Embedding(max_words,128),

    Bidirectional(
        LSTM(64)
    ),

    Dropout(0.3),

    Dense(1,activation='sigmoid')

])

bilstm.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

bilstm.fit(
    X_train_pad,
    y_train_encoded,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

gru = Sequential([

    Embedding(max_words,128),

    GRU(64),

    Dropout(0.3),

    Dense(1,activation='sigmoid')

])

gru.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

gru.fit(
    X_train_pad,
    y_train_encoded,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

bigru = Sequential([

    Embedding(max_words,128),

    Bidirectional(
        GRU(64)
    ),

    Dropout(0.3),

    Dense(1,activation='sigmoid')

])

bigru.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

bigru.fit(
    X_train_pad,
    y_train_encoded,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

models = {
    'CNN': cnn,
    'LSTM': lstm,
    'BiLSTM': bilstm,
    'GRU': gru,
    'BiGRU': bigru
}



results = []

for name, model in models.items():

    probs = model.predict(
        X_test_pad,
        verbose=0
    ).ravel()

    preds = (probs > 0.5).astype(int)

    results.append([

        name,

        accuracy_score(y_test_encoded,preds),

        precision_score(y_test_encoded,preds),

        recall_score(y_test_encoded,preds),

        f1_score(y_test_encoded,preds),

        roc_auc_score(y_test_encoded,probs)

    ])

results_df = pd.DataFrame(
    results,
    columns=[
        'Model',
        'Accuracy',
        'Precision',
        'Recall',
        'F1',
        'ROC_AUC'
    ]
)

results_df

results_df.set_index(
    'Model'
).plot(
    kind='bar',
    figsize=(14,6)
)

plt.title(
    'Deep Learning Model Comparison'
)

plt.ylabel('Score')

plt.xticks(rotation=20)

plt.grid(axis='y')

plt.show()

plt.figure(figsize=(8,6))

for name, model in models.items():

    probs = model.predict(
        X_test_pad,
        verbose=0
    ).ravel()

    fpr, tpr, _ = roc_curve(
        y_test_encoded,
        probs
    )

    roc_auc = auc(
        fpr,
        tpr
    )

    plt.plot(
        fpr,
        tpr,
        label=f'{name} (AUC={roc_auc:.3f})'
    )

plt.plot(
    [0,1],
    [0,1],
    linestyle='--'
)

plt.legend()

plt.title(
    'ROC Curve Comparison'
)

plt.show()

# Accuracy Ranking (Highest Accuracy on Top)

accuracy_chart = results_df.sort_values(
    by='Accuracy',
    ascending=False
)

plt.figure(figsize=(10,6))

bars = plt.bar(
    accuracy_chart['Model'],
    accuracy_chart['Accuracy']
)

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.002,
        f"{bar.get_height():.4f}",
        ha='center'
    )

plt.title(
    'Model Accuracy Comparison'
)

plt.ylabel('Accuracy')

plt.xlabel('Models')

plt.ylim(
    accuracy_chart['Accuracy'].min()-0.02,
    accuracy_chart['Accuracy'].max()+0.02
)

plt.xticks(rotation=20)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()

# Sort by Accuracy

accuracy_rank = results_df.sort_values(
    by='Accuracy',
    ascending=False
)

plt.figure(figsize=(10,6))

bars = plt.bar(
    accuracy_rank['Model'],
    accuracy_rank['Accuracy']
)

# Show values

for bar in bars:

    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.002,
        f"{bar.get_height():.4f}",
        ha='center'
    )

plt.title(
    'Deep Learning Models Ranked by Accuracy'
)

plt.xlabel('Models')

plt.ylabel('Accuracy')

plt.ylim(
    accuracy_rank['Accuracy'].min()-0.02,
    1.0
)

plt.grid(
    axis='y',
    linestyle='--',
    alpha=0.5
)

plt.show()

best_model = bigru

probs = best_model.predict(
    X_test_pad
).ravel()

preds = (probs > 0.5).astype(int)

cm = confusion_matrix(
    y_test_encoded,
    preds
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        'Negative',
        'Positive'
    ]
)

disp.plot()

plt.title(
    'BiGRU Confusion Matrix'
)

plt.show()

plt.figure(figsize=(8,6))

sns.heatmap(
    corr_matrix,
    annot=True,
    square=True,
    cmap='Blues',
    fmt='.2f'
)

plt.title(
    'Model Evaluation Metrics Correlation'
)

plt.tight_layout()

plt.show()